# Tutorial 1. Basic data types of the mmath_linalg and math_meigen libraries and operations with them

In this tutorial, we will learn:

* what data types are available in the mmath_linalg library
* what operations can be done with these data


In [1]:
import sys
import cmath
import math
import os

if sys.platform=="cygwin":
    from cyglibra_core import *
elif sys.platform=="linux" or sys.platform=="linux2":
    from liblibra_core import *
import util.libutil as comn

from libra_py import units
from libra_py import data_outs
import matplotlib.pyplot as plt   # plots
#matplotlib.use('Agg')
#%matplotlib inline 

import numpy as np
#from matplotlib.mlab import griddata

plt.rc('axes', titlesize=24)      # fontsize of the axes title
plt.rc('axes', labelsize=20)      # fontsize of the x and y labels
plt.rc('legend', fontsize=20)     # legend fontsize
plt.rc('xtick', labelsize=16)    # fontsize of the tick labels
plt.rc('ytick', labelsize=16)    # fontsize of the tick labels

plt.rc('figure.subplot', left=0.2)
plt.rc('figure.subplot', right=0.95)
plt.rc('figure.subplot', bottom=0.13)
plt.rc('figure.subplot', top=0.88)

colors = {}

colors.update({"11": "#8b1a0e"})  # red       
colors.update({"12": "#FF4500"})  # orangered 
colors.update({"13": "#B22222"})  # firebrick 
colors.update({"14": "#DC143C"})  # crimson   

colors.update({"21": "#5e9c36"})  # green
colors.update({"22": "#006400"})  # darkgreen  
colors.update({"23": "#228B22"})  # forestgreen
colors.update({"24": "#808000"})  # olive      

colors.update({"31": "#8A2BE2"})  # blueviolet
colors.update({"32": "#00008B"})  # darkblue  

colors.update({"41": "#2F4F4F"})  # darkslategray

clrs_index = ["11", "21", "31", "41", "12", "22", "32", "13","23", "14", "24"]

/home/alexey/miniconda2/envs/py37/lib/python3.7/importlib/_bootstrap.py:219: RuntimeWarning: to-Python converter for std::vector<std::vector<int, std::allocator<int> >, std::allocator<std::vector<int, std::allocator<int> > > > already registered; second conversion method ignored.
  return f(*args, **kwds)
/home/alexey/miniconda2/envs/py37/lib/python3.7/importlib/_bootstrap.py:219: RuntimeWarning: to-Python converter for boost::python::detail::container_element<std::vector<std::vector<int, std::allocator<int> >, std::allocator<std::vector<int, std::allocator<int> > > >, unsigned long, boost::python::detail::final_vector_derived_policies<std::vector<std::vector<int, std::allocator<int> >, std::allocator<std::vector<int, std::allocator<int> > > >, false> > already registered; second conversion method ignored.
  return f(*args, **kwds)
/home/alexey/miniconda2/envs/py37/lib/python3.7/importlib/_bootstrap.py:219: RuntimeWarning: to-Python converter for std::vector<std::vector<float, std::all

## 1. VECTOR

Objects of the `VECTOR` data type represent 3D points in Cartesian coordiantes. This is a natural data type for story coordinates, velocities, forces, and other similar properties of the physical point. 

Naturally, each obejct of this type has 3 components, x, y, z


\\[ v = (x , y, z)^T = 
\begin{pmatrix}
    x \\
    y \\
    z \\
\end{pmatrix}  
\\]      


### 1.1. Creation and initialization

The objects of this type can be created in a number of ways. The values of the components of the vector can be initialized at the moment of construction or later:

In [2]:
# Creating and empty vector
v1 = VECTOR()  
print(F"x = {v1.x} y = {v1.y} z = {v1.z}")

# Creating a vector with initialized components
v2 = VECTOR(1.0, -2.0, 3.0)
print(F"x = {v2.x} y = {v2.y} z = {v2.z}")

x = 0.0 y = 0.0 z = 0.0
x = 1.0 y = -2.0 z = 3.0


Note how `VECTOR()` is equivalent to `VECTOR(0.0, 0.0, 0.0)`

### 1.2. Copying

The best way to copy a vector object is via creating a new object taking the original object (that is being copied) as an argument. This is called a copy construction

In [3]:
v1 = VECTOR(1.0, -2.0, 3.0)
v2 = VECTOR(v1)

print(F"x = {v2.x} y = {v2.y} z = {v2.z}")

x = 1.0 y = -2.0 z = 3.0


Beware of the shallow copying (by reference).

Read more about it [here](https://github.com/compchem-cybertraining/Tutorials_Python/blob/master/Tutorial1-copying.ipynb)

Here is an example

In [4]:
v1 = VECTOR()
v2 = VECTOR()  

v2 = v1  # Copying by reference!



# Change v2 & print all vectors again
v2.x, v2.y, v2.z = 10.0, 10.0, 10.0
print("v1 = ", v1, v1.x, v1.y, v1.z)
print("v2 = ", v2, v2.x, v2.y, v2.z)


v1 =  <liblibra_core.VECTOR object at 0x7f33e0144db0> 10.0 10.0 10.0
v2 =  <liblibra_core.VECTOR object at 0x7f33e0144db0> 10.0 10.0 10.0


Print the initial variables

In [5]:
print("v1 = ", v1, v1.x, v1.y, v1.z)
print("v2 = ", v2, v2.x, v2.y, v2.z)

v1 =  <liblibra_core.VECTOR object at 0x7f33e0144db0> 10.0 10.0 10.0
v2 =  <liblibra_core.VECTOR object at 0x7f33e0144db0> 10.0 10.0 10.0


Note that when we "print" the objects, `v1` and `v2`, we actually print their addresses - the unique identitifiers that point to the memory location that stores these objects. Note how the addresses of the two distinctly-called variables are the same.

Now, lets change `v1` and print the two vectors again:

In [6]:
# Change v1 & print all vectors again
v1.x, v1.y, v1.z = 0.0, -1.0, 2.0
print("v1 = ", v1, v1.x, v1.y, v1.z)
print("v2 = ", v2, v2.x, v2.y, v2.z)

v1 =  <liblibra_core.VECTOR object at 0x7f33e0144db0> 0.0 -1.0 2.0
v2 =  <liblibra_core.VECTOR object at 0x7f33e0144db0> 0.0 -1.0 2.0


Note, how changing one variable changes the other. We would get the same result if we'd change `v2` instead.

### 1.3. Data access and Arithmetics

Lets create 3 vectors. 

In [7]:
v1 = VECTOR()  
v2 = VECTOR()  
v3 = VECTOR()  

print(F"v1: x = {v1.x} y = {v1.y} z = {v1.z} " )
print(F"v2: x = {v2.x} y = {v2.y} z = {v2.z} " )
print(F"v3: x = {v3.x} y = {v3.y} z = {v3.z} " )

v1: x = 0.0 y = 0.0 z = 0.0 
v2: x = 0.0 y = 0.0 z = 0.0 
v3: x = 0.0 y = 0.0 z = 0.0 


We can modify their data memebers, `x`, `y`, and `z` components directly:

In [8]:
v1.x, v1.y, v1.z =  1.0, 2.0, 1.0
v2.x, v2.y, v2.z = -1.0, 3.0, 0.0
v3.x, v3.y, v3.z =  0.0, 0.0, 0.0

print(F"v1: x = {v1.x} y = {v1.y} z = {v1.z} " )
print(F"v2: x = {v2.x} y = {v2.y} z = {v2.z} " )
print(F"v3: x = {v3.x} y = {v3.y} z = {v3.z} " )

v1: x = 1.0 y = 2.0 z = 1.0 
v2: x = -1.0 y = 3.0 z = 0.0 
v3: x = 0.0 y = 0.0 z = 0.0 


Then we can compute their sum, ddifference, any linear combinations as:

In [9]:
v3 = v1 + v2
print(F"sum: x = {v3.x} y = {v3.y} z = {v3.z} " )

v3 = v1 - v2
print(F"difference: x = {v3.x} y = {v3.y} z = {v3.z} " )

v3 = 2.0*v1 - v2*3.0
print(F"linear combination: x = {v3.x} y = {v3.y} z = {v3.z} " )

v3 = v1/2.0
print(F"division: x = {v3.x} y = {v3.y} z = {v3.z} " )

v3 = v1 * 2.0
print(F"multiplication: x = {v3.x} y = {v3.y} z = {v3.z} " )

sum: x = 0.0 y = 5.0 z = 1.0 
difference: x = 2.0 y = -1.0 z = 1.0 
linear combination: x = 5.0 y = -5.0 z = 2.0 
division: x = 0.5 y = 1.0 z = 0.5 
multiplication: x = 2.0 y = 4.0 z = 2.0 


We can also add/subtract a number from the vector, which is defined as adding/subtracting the same number from every element of the vector.

Analogously, we can increment or decrement the vectors by a number

In [10]:
print(F"v1 : x = {v1.x} y = {v1.y} z = {v1.z} " )

v3 = v1 + 1.0
print(F"v1 + 1 : x = {v3.x} y = {v3.y} z = {v3.z} " )

v3 = v1 - 1.0
print(F"v1 -= 1 : x = {v3.x} y = {v3.y} z = {v3.z} " )

v1 += 1.0
print(F"v1 += 1 : x = {v1.x} y = {v1.y} z = {v1.z} " )

v1 -= 1.0
print(F"(v1 +1) -= 1 : x = {v1.x} y = {v1.y} z = {v1.z} " )

v1 : x = 1.0 y = 2.0 z = 1.0 
v1 + 1 : x = 2.0 y = 3.0 z = 2.0 
v1 -= 1 : x = 0.0 y = 1.0 z = 0.0 
v1 += 1 : x = 2.0 y = 3.0 z = 2.0 
(v1 +1) -= 1 : x = 1.0 y = 2.0 z = 1.0 


The increments can also be by a vector:

In [11]:
v1 = VECTOR()
v2 = VECTOR(1.0, 2.0, 3.0)
print(F" v1 : x = {v1.x} y = {v1.y} z = {v1.z} " )

v1 += v2
print(F" v1 (after 1 increment) : x = {v1.x} y = {v1.y} z = {v1.z} " )

v1 += v2
print(F" v1 (after 2 increments) : x = {v1.x} y = {v1.y} z = {v1.z} " )

 v1 : x = 0.0 y = 0.0 z = 0.0 
 v1 (after 1 increment) : x = 1.0 y = 2.0 z = 3.0 
 v1 (after 2 increments) : x = 2.0 y = 4.0 z = 6.0 


The vectors can be scaled:

In [12]:
v2 = VECTOR(v1)
print(F"Original v1 : x = {v2.x} y = {v2.y} z = {v2.z} " )

v2 *= 2.0
print(F"Scaled by multiplication v1 : x = {v2.x} y = {v2.y} z = {v2.z} " )

v2 /= 2.0
print(F"Scaled by division v1 : x = {v2.x} y = {v2.y} z = {v2.z} " )

Original v1 : x = 2.0 y = 4.0 z = 6.0 
Scaled by multiplication v1 : x = 4.0 y = 8.0 z = 12.0 
Scaled by division v1 : x = 2.0 y = 4.0 z = 6.0 


### 1.4. Methods of the VECTOR class

The is a number of functions to compute properties of the vectors, including the computation of:

* the squared norm, `length2`

  $$ ||v||^2 = x^2 + y^2 + z^2  $$

* the norm, `length`

  $$ ||v|| = \sqrt{x^2 + y^2 + z^2}  $$
  
    

In [13]:
v1 = VECTOR(1.0, 1.0, 3.0)
print(F"v1: x = {v1.x} y = {v1.y} z = {v1.z} " )

print(F"|v1|^2 = ", v1.length2())
print(F"|v1| = ", v1.length())

v1: x = 1.0 y = 1.0 z = 3.0 
|v1|^2 =  11.0
|v1| =  3.3166247903554


We can also:

* normalize the original vector, `normalize`

  $$ v -> v = \frac{v}{||v||}$$

* or return the normalized (unit vector) without affecting the original one, `unit`

  $$ u = \frac{v}{||v||}$$

In [14]:
v = VECTOR(1.0, 1.0, 4.0)
u = v.unit()
print(F"v: x = {v.x} y = {v.y} z = {v.z} " )
print(F"u: x = {u.x} y = {u.y} z = {u.z} " )

v.normalize()
print(F"v: x = {v.x} y = {v.y} z = {v.z} " )

v: x = 1.0 y = 1.0 z = 4.0 
u: x = 0.23570226039551587 y = 0.23570226039551587 z = 0.9428090415820635 
v: x = 0.23570226039551587 y = 0.23570226039551587 z = 0.9428090415820635 


We can compute the cross product of 2 vectors:

$$
u \times v = 
\begin{vmatrix}
    i & j & k \\
    u_x & u_y & u_z \\
    v_x & v_y & v_z \\    
\end{vmatrix} =  \\
\begin{pmatrix}
    u_x * v_z - u_z * v_y \\
    u_z * v_x - u_x * v_z \\
    u_x * v_y - u_y * v_x \\    
\end{pmatrix}  
$$


In [15]:
v1 = VECTOR(1.0, 0.0, 0.0)
v2 = VECTOR(0.0, 1.0, 0.0)
v3 = VECTOR()
print(F"v1: x = {v1.x} y = {v1.y} z = {v1.z} " )
print(F"v2: x = {v2.x} y = {v2.y} z = {v2.z} " )


v3.cross(v1,v2)
print(F"v1 x v2 = {v3.x} y = {v3.y} z = {v3.z} " )

v3.cross(v2,v1)
print(F"v2 x v1 = {v3.x} y = {v3.y} z = {v3.z} " )

v3.cross(v1,v1)
print(F"v1 x v1 = {v3.x} y = {v3.y} z = {v3.z} " )

v1: x = 1.0 y = 0.0 z = 0.0 
v2: x = 0.0 y = 1.0 z = 0.0 
v1 x v2 = 0.0 y = 0.0 z = 1.0 
v2 x v1 = 0.0 y = 0.0 z = -1.0 
v1 x v1 = 0.0 y = 0.0 z = 0.0 


And, of course, we have the dot product:

$$
 v * u = ( v, u )  = v_x * u_x + v_y * u_y + v_z * u_z
$$

In [16]:
v1 = VECTOR(1.0, 3.0, 1.0)
v2 = VECTOR(2.0, 1.0, 4.0)
print(F"v1: x = {v1.x} y = {v1.y} z = {v1.z} " )
print(F"v2: x = {v2.x} y = {v2.y} z = {v2.z} " )

v12 = v1 * v2
print(F"v1 * v2 = {v12} " )

v1: x = 1.0 y = 3.0 z = 1.0 
v2: x = 2.0 y = 1.0 z = 4.0 
v1 * v2 = 9.0 


### 1.5. Arrays of vectors

We have a data type, `VECTORList`, that in C++ looks like vector< VECTOR > and represents a list of objects, each of which is a VECTOR object.

In Python, this can be just mimicked by a list of VECTOR objects:

In [17]:
vlst = VECTORList()

v1 = VECTOR(1.0, 3.0, 1.0)
v2 = VECTOR(2.0, 1.0, 4.0)
v3 = VECTOR(1.0, 0.0, -4.0)

vlst = [v1, v2, v3]
print(vlst)

for i in range(3):
    print(F"{i}: v = {vlst[i]} x = {vlst[i].x} y = {vlst[i].y} z = {vlst[i].z} ")

[<liblibra_core.VECTOR object at 0x7f339de1f3f0>, <liblibra_core.VECTOR object at 0x7f339de1f470>, <liblibra_core.VECTOR object at 0x7f339de23830>]
0: v = <liblibra_core.VECTOR object at 0x7f339de1f3f0> x = 1.0 y = 3.0 z = 1.0 
1: v = <liblibra_core.VECTOR object at 0x7f339de1f470> x = 2.0 y = 1.0 z = 4.0 
2: v = <liblibra_core.VECTOR object at 0x7f339de23830> x = 1.0 y = 0.0 z = -4.0 


## 2. MATRIX and CMATRIX

Objects of the MATRIX and CMATRIX data types represent real and complex-valued matrices of arbitrary shape.

These classes share a lot of common functionality (data members and function members), with a few exceptions.

### 2.1. Initialization and data access

* use `MATRIX(n,m)` or `CMATRIX(n,m)` to allocate empty matrices of the corresponding shapes

* use `.set(i,j, val)` to store the value `val` in the corresponding matrix element

* use `.get(i,j)` to read/access the value stored in the corresponding matrix element

* use `.show_matrix` to print out the matrix to the standard output (usually consolde). 

Note that the "show_matrix" function would not print the results to the Jupyter output. Instead, use

`data_outs.print_matrix`

In [18]:
a = MATRIX(3,3)

for i in range(0,3):
    for j in range(0,3):
        a.set(i,j, 0.1+0.1*(i+j) )

for i in range(0,3):
    for j in range(0,3):
        print(i,j, a.get(i,j) )

a.show_matrix()
print("=========== matrix a ===============")
data_outs.print_matrix(a)

0 0 0.1
0 1 0.2
0 2 0.30000000000000004
1 0 0.2
1 1 0.30000000000000004
1 2 0.4
2 0 0.30000000000000004
2 1 0.4
2 2 0.5
=========== matrix a ===============
0.1  0.2  0.30000000000000004  
0.2  0.30000000000000004  0.4  
0.30000000000000004  0.4  0.5  


Here is an example for complex matrices

In [19]:
a = CMATRIX(4,4)
for i in range(0,4):
    for j in range(0,4):
        a.set(i,j,0.5*i+j, 0.1*(i-j))

for i in range(0,4):
    for j in range(0,4):
        print( i,j, a.get(i,j) )

        
data_outs.print_matrix(a)

0 0 0j
0 1 (1-0.1j)
0 2 (2-0.2j)
0 3 (3-0.30000000000000004j)
1 0 (0.5+0.1j)
1 1 (1.5+0j)
1 2 (2.5-0.1j)
1 3 (3.5-0.2j)
2 0 (1+0.2j)
2 1 (2+0.1j)
2 2 (3+0j)
2 3 (4-0.1j)
3 0 (1.5+0.30000000000000004j)
3 1 (2.5+0.2j)
3 2 (3.5+0.1j)
3 3 (4.5+0j)
0j  (1-0.1j)  (2-0.2j)  (3-0.30000000000000004j)  
(0.5+0.1j)  (1.5+0j)  (2.5-0.1j)  (3.5-0.2j)  
(1+0.2j)  (2+0.1j)  (3+0j)  (4-0.1j)  
(1.5+0.30000000000000004j)  (2.5+0.2j)  (3.5+0.1j)  (4.5+0j)  


### 2.2. Computing some basic properties of a matrix

* trace
* transpose
* conjugate
* Hermitian conjugate
* identity matrix
* columns
* rows

In [20]:
# Trace
print( "trace = ", a.tr() )

# Transpose 
x = a.T()
print("print a"); data_outs.print_matrix(a)
print("print x"); data_outs.print_matrix(x)

# Conjugate
x = a.conj()
print("print a"); data_outs.print_matrix(a)
print("print x"); data_outs.print_matrix(x)

# Hermitian conjugate
x = a.H()
print("print a"); data_outs.print_matrix(a)
print("print x"); data_outs.print_matrix(x)

# Initilize an identity matrix
x.load_identity(); data_outs.print_matrix(x)

# Accessing columns
t1 = a.col(0); data_outs.print_matrix(t1)

# Accessing rows
t2 = a.row(2); data_outs.print_matrix(t2)

trace =  (9+0j)
print a
0j  (1-0.1j)  (2-0.2j)  (3-0.30000000000000004j)  
(0.5+0.1j)  (1.5+0j)  (2.5-0.1j)  (3.5-0.2j)  
(1+0.2j)  (2+0.1j)  (3+0j)  (4-0.1j)  
(1.5+0.30000000000000004j)  (2.5+0.2j)  (3.5+0.1j)  (4.5+0j)  
print x
0j  (0.5+0.1j)  (1+0.2j)  (1.5+0.30000000000000004j)  
(1-0.1j)  (1.5+0j)  (2+0.1j)  (2.5+0.2j)  
(2-0.2j)  (2.5-0.1j)  (3+0j)  (3.5+0.1j)  
(3-0.30000000000000004j)  (3.5-0.2j)  (4-0.1j)  (4.5+0j)  
print a
0j  (1-0.1j)  (2-0.2j)  (3-0.30000000000000004j)  
(0.5+0.1j)  (1.5+0j)  (2.5-0.1j)  (3.5-0.2j)  
(1+0.2j)  (2+0.1j)  (3+0j)  (4-0.1j)  
(1.5+0.30000000000000004j)  (2.5+0.2j)  (3.5+0.1j)  (4.5+0j)  
print x
-0j  (1+0.1j)  (2+0.2j)  (3+0.30000000000000004j)  
(0.5-0.1j)  (1.5-0j)  (2.5+0.1j)  (3.5+0.2j)  
(1-0.2j)  (2-0.1j)  (3-0j)  (4+0.1j)  
(1.5-0.30000000000000004j)  (2.5-0.2j)  (3.5-0.1j)  (4.5-0j)  
print a
0j  (1-0.1j)  (2-0.2j)  (3-0.30000000000000004j)  
(0.5+0.1j)  (1.5+0j)  (2.5-0.1j)  (3.5-0.2j)  
(1+0.2j)  (2+0.1j)  (3+0j)  (4-0.1j)  
(1.5+0

### 2.3. Manipulating matrices

In [21]:
N = 5
A = MATRIX(N,N)
B = MATRIX(N,N)
for i in range(0,N):
    for j in range(0,N):
        A.set(i,j,-2.0*i+j*j )
        B.set(i,j,0.0 )

print("The original matrix A")
data_outs.print_matrix(A)

print("The original matrix B")
data_outs.print_matrix(B)


a2x2 = MATRIX(2,2)
print("Extracting with stencil [0,1]")
pop_submatrix(A,a2x2, [0,1]); data_outs.print_matrix(a2x2)

print("Extracting with stencil [3,4]")
pop_submatrix(A,a2x2, [3,4]); data_outs.print_matrix(a2x2)

print("Extracting with stencil [1,3]")
pop_submatrix(A,a2x2, [1,3]); data_outs.print_matrix(a2x2)

print("Pushing 2x2 matrix with stencil [0,1]")
push_submatrix(B,a2x2, [0,1]); data_outs.print_matrix(B)


The original matrix A
0.0  1.0  4.0  9.0  16.0  
-2.0  -1.0  2.0  7.0  14.0  
-4.0  -3.0  0.0  5.0  12.0  
-6.0  -5.0  -2.0  3.0  10.0  
-8.0  -7.0  -4.0  1.0  8.0  
The original matrix B
0.0  0.0  0.0  0.0  0.0  
0.0  0.0  0.0  0.0  0.0  
0.0  0.0  0.0  0.0  0.0  
0.0  0.0  0.0  0.0  0.0  
0.0  0.0  0.0  0.0  0.0  
Extracting with stencil [0,1]
0.0  1.0  
-2.0  -1.0  
Extracting with stencil [3,4]
3.0  10.0  
1.0  8.0  
Extracting with stencil [1,3]
-1.0  7.0  
-5.0  3.0  
Pushing 2x2 matrix with stencil [0,1]
-1.0  7.0  0.0  0.0  0.0  
-5.0  3.0  0.0  0.0  0.0  
0.0  0.0  0.0  0.0  0.0  
0.0  0.0  0.0  0.0  0.0  
0.0  0.0  0.0  0.0  0.0  


In [22]:
B = B*0.0

a3x3 = MATRIX(3,3)
print("Extracting 3x3 matrix with stencil [0,1,2]")
pop_submatrix(A,a3x3, [0,1,2]); data_outs.print_matrix(a3x3)

print("Pushing 3x3 matrix into B with stencil [0,3,4]")
push_submatrix(B,a3x3, [0,3,4]); data_outs.print_matrix(B)

print("Pushing another, a 2x2, matrix into B with stencil [0,1]")
push_submatrix(B,a2x2, [0,1]); data_outs.print_matrix(B)


Extracting 3x3 matrix with stencil [0,1,2]
0.0  1.0  4.0  
-2.0  -1.0  2.0  
-4.0  -3.0  0.0  
Pushing 3x3 matrix into B with stencil [0,3,4]
0.0  0.0  0.0  1.0  4.0  
-0.0  0.0  0.0  0.0  0.0  
0.0  0.0  0.0  0.0  0.0  
-2.0  0.0  0.0  -1.0  2.0  
-4.0  0.0  0.0  -3.0  0.0  
Pushing another, a 2x2, matrix into B with stencil [0,1]
-1.0  7.0  0.0  1.0  4.0  
-5.0  3.0  0.0  0.0  0.0  
0.0  0.0  0.0  0.0  0.0  
-2.0  0.0  0.0  -1.0  2.0  
-4.0  0.0  0.0  -3.0  0.0  


In [23]:
print("The original matrix A")
data_outs.print_matrix(A)


a2x3 = MATRIX(2,3)
print("Extracting 2x3 matrix with stencils [2,4] and [1,3,4]")
pop_submatrix(A,a2x3, [2,4],[1,3,4]); data_outs.print_matrix(a2x3)

print("Extracting 2x3 matrix with stencils [0,1] and [2,3,4]")
pop_submatrix(A,a2x3, [0,1],[2,3,4]); data_outs.print_matrix(a2x3)


a3x2 = MATRIX(3,2)
print("Extracting 3x2 matrix with stencils [2,3,4] and [0,1]")
pop_submatrix(A,a3x2, [2,3,4],[0,1]); data_outs.print_matrix(a3x2)


B = B*0.0
print("Pushing 2x3 matrix with stencils [3,4] and [0,1,2]")
push_submatrix(B,a2x3, [3,4],[0,1,2]); data_outs.print_matrix(B)

print( "Pushing 3x2 matrix with stencils [0,1,2] and [3,4]")
push_submatrix(B,a3x2, [0,1,2],[3,4]); data_outs.print_matrix(B)



The original matrix A
0.0  1.0  4.0  9.0  16.0  
-2.0  -1.0  2.0  7.0  14.0  
-4.0  -3.0  0.0  5.0  12.0  
-6.0  -5.0  -2.0  3.0  10.0  
-8.0  -7.0  -4.0  1.0  8.0  
Extracting 2x3 matrix with stencils [2,4] and [1,3,4]
-3.0  5.0  12.0  
-7.0  1.0  8.0  
Extracting 2x3 matrix with stencils [0,1] and [2,3,4]
4.0  9.0  16.0  
2.0  7.0  14.0  
Extracting 3x2 matrix with stencils [2,3,4] and [0,1]
-4.0  -3.0  
-6.0  -5.0  
-8.0  -7.0  
Pushing 2x3 matrix with stencils [3,4] and [0,1,2]
-0.0  0.0  0.0  0.0  0.0  
-0.0  0.0  0.0  0.0  0.0  
0.0  0.0  0.0  0.0  0.0  
4.0  9.0  16.0  -0.0  0.0  
2.0  7.0  14.0  -0.0  0.0  
Pushing 3x2 matrix with stencils [0,1,2] and [3,4]
-0.0  0.0  0.0  -4.0  -3.0  
-0.0  0.0  0.0  -6.0  -5.0  
0.0  0.0  0.0  -8.0  -7.0  
4.0  9.0  16.0  -0.0  0.0  
2.0  7.0  14.0  -0.0  0.0  


### 2.4. Matrix arithmetics

In [24]:
A = MATRIX(2,2)
A.set(0,0, 1.0);   A.set(0,1, 2.0);
A.set(1,0, -1.0);  A.set(1,1, 0.5);
data_outs.print_matrix(A)

#========= Scaling: Example 1 ==============
B = MATRIX(2,2)
B.set(0,0, 1.0);   B.set(0,1, 1.0);
B.set(1,0, 1.0);   B.set(1,1, 1.0);
data_outs.print_matrix(B)

C = MATRIX(2,2)

# dot product
C.dot_product(A,B)
data_outs.print_matrix(C)

#========= Scaling: Example 2 ==============
B.set(0,0, 1.0);   B.set(0,1, 0.1);
B.set(1,0, 10.0);  B.set(1,1, 1.0);
C.dot_product(A,B)

print("Scaling matrix"); data_outs.print_matrix(B)
print("Original matrix"); data_outs.print_matrix(A)
print("Result"); data_outs.print_matrix(C)


#========= Scaling: Example 3 ==============
# What if one of matrices is also used to store the result
print("Original matrix"); data_outs.print_matrix(A)
B.set(0,0, 1.0);   B.set(0,1, 0.1);
B.set(1,0, 10.0);  B.set(1,1, 1.0);
A.dot_product(A,B)

print("Scaling matrix"); data_outs.print_matrix(B)
print("Result"); data_outs.print_matrix(A)


1.0  2.0  
-1.0  0.5  
1.0  1.0  
1.0  1.0  
1.0  2.0  
-1.0  0.5  
Scaling matrix
1.0  0.1  
10.0  1.0  
Original matrix
1.0  2.0  
-1.0  0.5  
Result
1.0  0.2  
-10.0  0.5  
Original matrix
1.0  2.0  
-1.0  0.5  
Scaling matrix
1.0  0.1  
10.0  1.0  
Result
1.0  0.2  
-10.0  0.5  


### 2.5. Eigenvalue solvers

We are solving the problem

\\[ H C = S C E \\]

In [25]:
# Init the matrix
H = MATRIX(2,2)
H.set(0,0, -0.001);  H.set(0,1, 0.001)
H.set(1,0, 0.001);   H.set(1,1,  0.001)

# Convert to a complex data type
cH = CMATRIX(H); 

print("H = \n"); data_outs.print_matrix(H)
print("cH = \n"); data_outs.print_matrix(cH)


# Overlap 
S = MATRIX(2,2)
S.set(0,0, 1.0);   S.set(0,1, 0.5)
S.set(1,0, 0.5);   S.set(1,1, 1.0)

# Convert to a complex data type
cS = CMATRIX(S); 

print("S = \n"); data_outs.print_matrix(S)
print("cS = \n"); data_outs.print_matrix(cS)

# Eigenvectors (C) and Eigenvalues (E)
E = MATRIX(2,2);  cE = CMATRIX(2,2)
C = MATRIX(2,2);  cC = CMATRIX(2,2)


H = 

-0.001  0.001  
0.001  0.001  
cH = 

(-0.001+0j)  (0.001+0j)  
(0.001+0j)  (0.001+0j)  
S = 

1.0  0.5  
0.5  1.0  
cS = 

(1+0j)  (0.5+0j)  
(0.5+0j)  (1+0j)  


There are several versions of the eigensolver

**1. generalized, real H and S, real C and E**

In [26]:
# Solving the generalized eigenvalue problem
solve_eigen(H, S, E, C, 0);

print("E = "); data_outs.print_matrix(E)
print("\nC = "); data_outs.print_matrix(C)
print("\nH*C = "); data_outs.print_matrix(H*C)
print("\nS*C*E = (should be the same as the expr above) "); data_outs.print_matrix(S*C*E)
print("\nC.T() * S * C = (should be the identity matrix)"); data_outs.print_matrix(C.T() * S * C)

E = 
-0.0024305008740430605  0.0  
0.0  0.0010971675407097272  

C = 
-1.1386867238250293  -0.19163997056447962  
0.7353084448018562  -0.8903116445023108  

H*C = 
0.0018739951686268855  -0.0006986716739378312  
-0.0004033782790231731  -0.0010819516150667905  

S*C*E = (should be the same as the expr above) 
0.0018739951686268855  -0.0006986716739378313  
-0.00040337827902317357  -0.0010819516150667905  

C.T() * S * C = (should be the identity matrix)
1.0  -1.3877787807814457e-16  
-1.1102230246251565e-16  1.0  


**2. generalized, real H and S, complex C and E**

In [27]:
# Solving the generalized eigenvalue problem
solve_eigen(H, S, cE, cC, 0);

print("E = "); data_outs.print_matrix(cE)
print("\nC = "); data_outs.print_matrix(cC)
print("\nH*C = "); data_outs.print_matrix(cH*cC)
print("\nS*C*E = (should be the same as the expr above) "); data_outs.print_matrix(cS*cC*cE)
print("\nC.H() * S * C = (should be the identity matrix)"); data_outs.print_matrix(cC.H() * cS * cC)

E = 
(-0.0024305008740430605+0j)  0j  
0j  (0.0010971675407097272+0j)  

C = 
(-1.1386867238250293+0j)  (-0.19163997056447962-0j)  
(0.7353084448018562+0j)  (-0.8903116445023108-0j)  

H*C = 
(0.0018739951686268855+0j)  (-0.0006986716739378312+0j)  
(-0.0004033782790231731+0j)  (-0.0010819516150667905+0j)  

S*C*E = (should be the same as the expr above) 
(0.0018739951686268855+0j)  (-0.0006986716739378313+0j)  
(-0.00040337827902317357+0j)  (-0.0010819516150667905+0j)  

C.H() * S * C = (should be the identity matrix)
(1+0j)  (-1.3877787807814457e-16+0j)  
(-1.1102230246251565e-16+0j)  (1+0j)  


**3. Non-generalized, complex H and S, complex C and E**

In [28]:
# Solving the generalized eigenvalue problem
solve_eigen(cH, cS, cE, cC, 0);

print("E = "); data_outs.print_matrix(cE)
print("\nC = "); data_outs.print_matrix(cC)
print("\nH*C = "); data_outs.print_matrix(cH*cC)
print("\nS*C*E = (should be the same as the expr above) "); data_outs.print_matrix(cS*cC*cE)
print("\nC.H() * S * C = (should be the identity matrix)"); data_outs.print_matrix(cC.H() * cS * cC)

E = 
(-0.0024305008740430605+0j)  0j  
0j  (0.0010971675407097272+0j)  

C = 
(-1.1386867238250293+0j)  (-0.19163997056447962-0j)  
(0.7353084448018562+0j)  (-0.8903116445023108-0j)  

H*C = 
(0.0018739951686268855+0j)  (-0.0006986716739378312+0j)  
(-0.0004033782790231731+0j)  (-0.0010819516150667905+0j)  

S*C*E = (should be the same as the expr above) 
(0.0018739951686268855+0j)  (-0.0006986716739378313+0j)  
(-0.00040337827902317357+0j)  (-0.0010819516150667905+0j)  

C.H() * S * C = (should be the identity matrix)
(1+0j)  (-1.3877787807814457e-16+0j)  
(-1.1102230246251565e-16+0j)  (1+0j)  


**4. Non-generalized, real H, real C and E**

In [29]:
# Solving the generalized eigenvalue problem
solve_eigen(H, E, C, 0);

print("E = "); data_outs.print_matrix(E)
print("\nC = "); data_outs.print_matrix(C)
print("\nH*C = "); data_outs.print_matrix(H*C)
print("\nC*E = (should be the same as the expr above) "); data_outs.print_matrix(C*E)
print("\nC.T() * C = (should be the identity matrix)"); data_outs.print_matrix(C.T() * C)

E = 
-0.001414213562373095  0.0  
0.0  0.001414213562373095  

C = 
-0.9238795325112867  -0.3826834323650898  
0.3826834323650898  -0.9238795325112867  

H*C = 
0.0013065629648763765  -0.000541196100146197  
-0.000541196100146197  -0.0013065629648763765  

C*E = (should be the same as the expr above) 
0.0013065629648763765  -0.000541196100146197  
-0.000541196100146197  -0.0013065629648763765  

C.T() * C = (should be the identity matrix)
1.0  0.0  
0.0  1.0  


**5. Non-generalized, real H and S, complex C and E**

In [30]:
# Solving the generalized eigenvalue problem
solve_eigen(H, cE, cC, 0);

print("E = "); data_outs.print_matrix(cE)
print("\nC = "); data_outs.print_matrix(cC)
print("\nH*C = "); data_outs.print_matrix(cH*cC)
print("\nC*E = (should be the same as the expr above) "); data_outs.print_matrix(cC*cE)
print("\nC.H() * C = (should be the identity matrix)"); data_outs.print_matrix(cC.H() * cC)

E = 
(-0.001414213562373095+0j)  0j  
0j  (0.001414213562373095+0j)  

C = 
(-0.9238795325112867+0j)  (-0.3826834323650898-0j)  
(0.3826834323650898+0j)  (-0.9238795325112867-0j)  

H*C = 
(0.0013065629648763765+0j)  (-0.000541196100146197+0j)  
(-0.000541196100146197+0j)  (-0.0013065629648763765+0j)  

C*E = (should be the same as the expr above) 
(0.0013065629648763765+0j)  (-0.000541196100146197+0j)  
(-0.000541196100146197+0j)  (-0.0013065629648763765+0j)  

C.H() * C = (should be the identity matrix)
(1+0j)  0j  
0j  (1+0j)  


**6. Non-generalized, complex H and S, complex C and E**

In [31]:
# Solving the generalized eigenvalue problem
solve_eigen(cH, cE, cC, 0);

print("E = "); data_outs.print_matrix(cE)
print("\nC = "); data_outs.print_matrix(cC)
print("\nH*C = "); data_outs.print_matrix(cH*cC)
print("\nC*E = (should be the same as the expr above) "); data_outs.print_matrix(cC*cE)
print("\nC.H() * C = (should be the identity matrix)"); data_outs.print_matrix(cC.H() * cC)

E = 
(-0.001414213562373095+0j)  0j  
0j  (0.001414213562373095+0j)  

C = 
(-0.9238795325112867+0j)  (-0.3826834323650898-0j)  
(0.3826834323650898+0j)  (-0.9238795325112867-0j)  

H*C = 
(0.0013065629648763765+0j)  (-0.000541196100146197+0j)  
(-0.000541196100146197+0j)  (-0.0013065629648763765+0j)  

C*E = (should be the same as the expr above) 
(0.0013065629648763765+0j)  (-0.000541196100146197+0j)  
(-0.000541196100146197+0j)  (-0.0013065629648763765+0j)  

C.H() * C = (should be the identity matrix)
(1+0j)  0j  
0j  (1+0j)  
