In [2]:
import os
import sys
import numpy as np
import scipy.sparse as sp
from libra_py import CP2K_methods
from libra_py.workflows.nbra import step2

In [2]:
!module load intel/20.2
!module load intel-mpi/2020.2

 The Intel 20.2 compilers are in your path. This is adequate for compiling and
running most codes. Source compilervars.sh for more features including the
debugger. 
 The Intel MPI 2020.2 is in your path. This is adequate for compiling and
running most codes. Run "source
/util/academic/intel/20.2/compilers_and_libraries_2020.2.254/linux/mpi/intel64/bin/mpivars.sh"
for more features including the debugger. 


In [5]:
path = os.getcwd()
params = {}
# number of processors

params['nprocs'] = 12
# The istep and fstep
params['istep'] = 1
params['fstep'] = 5
# Lowest and highest orbital, Here HOMO is 128
params['init_state'] = 128-20
params['final_state'] = 128+21
# extended tight-binding calculation type
params['isxTB'] = True
# DFT calculation type
params['isUKS'] = False
# Periodic calculations flag
params['is_periodic'] = True
# Set the cell parameters for periodic calculations
if params['is_periodic']:
    params['A_cell_vector'] = [14.2415132523,0.0000000000,0.0000000000]
    params['B_cell_vector'] = [0.0002151559,12.3343009930,0.0000000000]
    # The vacuum 
    params['C_cell_vector'] = [0.0018975023,0.0028002808,14.9999996186]
    params['periodicity_type'] = 'XY'
    # Set the origin
    origin = [0,0,0]
    tr_vecs = params['translational_vectors'] = CP2K_methods.generate_translational_vectors(origin, [1,1,1],
                                                                                            params['periodicity_type'])
    
    print('The translational vectors for the current periodic system are:\n')
    print(tr_vecs)
    print(F'Will compute the S^AO between R(0,0,0) and {tr_vecs.shape[0]+1} translational vectors')

# The AO overlaps in spherical or Cartesian coordinates
params['is_spherical'] =  True
# Remove the molden files, which are large files for some systems, 
# after the computaion is done for tha system
params['remove_molden'] = True
# The results are stored in this folder
params['res_dir'] = path + '/res'
params['all_pdosfiles'] = path + '/all_pdosfiles'
params['all_logfiles'] = path + '/all_logfiles'
# CP2K executable 
params['cp2k_exe'] = '/projects/academic/cyberwksp21/Software/cp2k-intel/cp2k-8.2/exe/Linux-x86-64-intelx/cp2k.psmp'
# If the xTB calculations are needed, we need an OT procedure 
params['cp2k_ot_input_template'] = path + '/es_ot_temp.inp'
params['cp2k_diag_input_template'] = path + '/es_diag_temp.inp'
# The trajectory xyz file path
params['trajectory_xyz_filename'] = path + '/../../../6_step1_cp2k/2_xTB/c3n4_1x1_MD_xTB-pos-1.xyz'

step2.run_cp2k_libint_step2(params)

The translational vectors for the current periodic system are:

[[-1 -1  0]
 [-1  0  0]
 [-1  1  0]
 [ 0 -1  0]
 [ 0  1  0]
 [ 1 -1  0]
 [ 1  0  0]
 [ 1  1  0]]
Will compute the S^AO between R(0,0,0) and 9 translational vectors
-----------------------Start-----------------------
-----------------------Step 1-----------------------
**************** Running CP2K ****************
Step 1 Computing the OT method wfn file...
Done with OT wfn. Elapsed time: 1.9777138233184814
Computing the wfn file using diagonalization method...
Done with diagonalization. Elapsed time: 1.1838455200195312
Done with step 1 Elapsed time: 3.188774347305298
Creating shell...
Done with creating shell. Elapsed time: 0.04091310501098633
Reading energies and eigenvectors....
Done with reading energies and eigenvectors. Elapsed time: 0.15270137786865234
Computing atomic orbital overlap matrix...
Computing the AO overlaps between R(-1,-1,0) and R(0,0,0)
Computing the AO overlaps between R(-1,0,0) and R(0,0,0)
Computing

In [6]:
# Load sample file for S and St matrices and then 
# print the diagonal to check the orthonormality of the wavefunctions
S = sp.load_npz('res/S_ks_1.npz').todense()
print('S matrix:\n',np.diag(S))
St = sp.load_npz('res/St_ks_1.npz').todense()
print('St matrix:\n',np.diag(St))

S matrix:
 [0.99999975+0.j 0.99999986+0.j 0.99999972+0.j 0.99999967+0.j
 0.9999997 +0.j 0.99999987+0.j 0.99999988+0.j 0.99999983+0.j
 0.99999978+0.j 0.99999963+0.j 0.99999965+0.j 0.99999948+0.j
 0.99999988+0.j 0.99999989+0.j 0.99999967+0.j 0.99999968+0.j
 0.99999949+0.j 0.99999952+0.j 0.99999953+0.j 0.99999944+0.j
 0.9999998 +0.j 0.99999963+0.j 0.99999959+0.j 0.9999996 +0.j
 0.99999966+0.j 0.99999954+0.j 0.99999959+0.j 0.99999962+0.j
 0.99999945+0.j 0.9999994 +0.j 0.99999955+0.j 0.99999937+0.j
 0.99999949+0.j 0.99999941+0.j 0.9999993 +0.j 0.99999941+0.j
 0.99999928+0.j 0.99999925+0.j 0.99999927+0.j 0.99999927+0.j
 0.99999922+0.j 0.99999923+0.j 0.99999975+0.j 0.99999986+0.j
 0.99999972+0.j 0.99999967+0.j 0.9999997 +0.j 0.99999987+0.j
 0.99999988+0.j 0.99999983+0.j 0.99999978+0.j 0.99999963+0.j
 0.99999965+0.j 0.99999948+0.j 0.99999988+0.j 0.99999989+0.j
 0.99999967+0.j 0.99999968+0.j 0.99999949+0.j 0.99999952+0.j
 0.99999953+0.j 0.99999944+0.j 0.9999998 +0.j 0.99999963+0.j
 0.99999959+0