In [4]:
import os
import sys
import numpy as np
import scipy.sparse as sp
from libra_py import CP2K_methods
from libra_py.workflows.nbra import step2

In [2]:
!module load intel/20.2
!module load intel-mpi/2020.2

 The Intel 20.2 compilers are in your path. This is adequate for compiling and
running most codes. Source compilervars.sh for more features including the
debugger. 
 The Intel MPI 2020.2 is in your path. This is adequate for compiling and
running most codes. Run "source
/util/academic/intel/20.2/compilers_and_libraries_2020.2.254/linux/mpi/intel64/bin/mpivars.sh"
for more features including the debugger. 


In [11]:
path = os.getcwd()
params = {}
# number of processors

params['nprocs'] = 12
# The istep and fstep
params['istep'] = 1
params['fstep'] = 5
# Lowest and highest orbital, Here HOMO is 24
params['init_state'] = 24-10
params['final_state'] = 24+11
# extended tight-binding calculation type
params['isxTB'] = False
# DFT calculation type
params['isUKS'] = False
# Periodic calculations flag
params['is_periodic'] = True
# Set the cell parameters for periodic calculations
if params['is_periodic']:
    params['A_cell_vector'] = [4.6532721519, 0.0000000000, 0.0000000000]
    params['B_cell_vector'] = [0.0000000000, 4.6532721519, 0.0000000000]
    params['C_cell_vector'] = [0.0000000000, 0.0000000000, 2.9692029953]
    params['periodicity_type'] = 'XYZ'
    # Set the origin
    origin = [0,0,0]
    # Only in case params['periodicity_type'] = 'manual'
    tr_vecs = params['translational_vectors'] = CP2K_methods.generate_translational_vectors(origin, [2,2,2],
                                                                                            params['periodicity_type'])
    
    print('The translational vectors for the current periodic system are:\n')
    print(tr_vecs)
    print(F'Will compute the S^AO between R(0,0,0) and {tr_vecs.shape[0]+1} translational vectors')

# The AO overlaps in spherical or Cartesian coordinates
params['is_spherical'] =  True
# Remove the molden files, which are large files for some systems, 
# after the computaion is done for tha system
params['remove_molden'] = True
# The results are stored in this folder
params['res_dir'] = path + '/res'
params['all_pdosfiles'] = path + '/all_pdosfiles'
params['all_logfiles'] = path + '/all_logfiles'
# CP2K executable 
params['cp2k_exe'] = '/projects/academic/cyberwksp21/Software/cp2k-intel/cp2k-8.2/exe/Linux-x86-64-intelx/cp2k.psmp'
# If the xTB calculations are needed, we need an OT procedure 
params['cp2k_ot_input_template'] = path + '/es_ot_temp.inp'
params['cp2k_diag_input_template'] = path + '/es_diag_temp.inp'
# The trajectory xyz file path
params['trajectory_xyz_filename'] = path + '/../../../6_step1_cp2k/1_DFT/Rutile_TiO2_MD-pos-1.xyz'

step2.run_cp2k_libint_step2(params)

The translational vectors for the current periodic system are:

[[-2 -2 -2]
 [-2 -2 -1]
 [-2 -2  0]
 [-2 -2  1]
 [-2 -2  2]
 [-2 -1 -2]
 [-2 -1 -1]
 [-2 -1  0]
 [-2 -1  1]
 [-2 -1  2]
 [-2  0 -2]
 [-2  0 -1]
 [-2  0  0]
 [-2  0  1]
 [-2  0  2]
 [-2  1 -2]
 [-2  1 -1]
 [-2  1  0]
 [-2  1  1]
 [-2  1  2]
 [-2  2 -2]
 [-2  2 -1]
 [-2  2  0]
 [-2  2  1]
 [-2  2  2]
 [-1 -2 -2]
 [-1 -2 -1]
 [-1 -2  0]
 [-1 -2  1]
 [-1 -2  2]
 [-1 -1 -2]
 [-1 -1 -1]
 [-1 -1  0]
 [-1 -1  1]
 [-1 -1  2]
 [-1  0 -2]
 [-1  0 -1]
 [-1  0  0]
 [-1  0  1]
 [-1  0  2]
 [-1  1 -2]
 [-1  1 -1]
 [-1  1  0]
 [-1  1  1]
 [-1  1  2]
 [-1  2 -2]
 [-1  2 -1]
 [-1  2  0]
 [-1  2  1]
 [-1  2  2]
 [ 0 -2 -2]
 [ 0 -2 -1]
 [ 0 -2  0]
 [ 0 -2  1]
 [ 0 -2  2]
 [ 0 -1 -2]
 [ 0 -1 -1]
 [ 0 -1  0]
 [ 0 -1  1]
 [ 0 -1  2]
 [ 0  0 -2]
 [ 0  0 -1]
 [ 0  0  1]
 [ 0  0  2]
 [ 0  1 -2]
 [ 0  1 -1]
 [ 0  1  0]
 [ 0  1  1]
 [ 0  1  2]
 [ 0  2 -2]
 [ 0  2 -1]
 [ 0  2  0]
 [ 0  2  1]
 [ 0  2  2]
 [ 1 -2 -2]
 [ 1 -2 -1]
 [ 1 -2  0]
 [ 1 -2  1]


Done with computing molecular orbital overlaps. Elapsed time: 0.03754138946533203
Done with step 1. Elapsed time: 44.55493879318237
-----------------------Step 2-----------------------
Done with step 2 Elapsed time: 41.30417275428772
Creating shell...
Done with creating shell. Elapsed time: 0.015007972717285156
Reading energies and eigenvectors....
Done with reading energies and eigenvectors. Elapsed time: 0.0476837158203125
Computing atomic orbital overlap matrix...
Computing the AO overlaps between R(-2,-2,-2) and R(0,0,0)
Computing the AO overlaps between R(-2,-2,-1) and R(0,0,0)
Computing the AO overlaps between R(-2,-2,0) and R(0,0,0)
Computing the AO overlaps between R(-2,-2,1) and R(0,0,0)
Computing the AO overlaps between R(-2,-2,2) and R(0,0,0)
Computing the AO overlaps between R(-2,-1,-2) and R(0,0,0)
Computing the AO overlaps between R(-2,-1,-1) and R(0,0,0)
Computing the AO overlaps between R(-2,-1,0) and R(0,0,0)
Computing the AO overlaps between R(-2,-1,1) and R(0,0,0)
Co

Computing the AO overlaps between R(-2,1,1) and R(0,0,0)
Computing the AO overlaps between R(-2,1,2) and R(0,0,0)
Computing the AO overlaps between R(-2,2,-2) and R(0,0,0)
Computing the AO overlaps between R(-2,2,-1) and R(0,0,0)
Computing the AO overlaps between R(-2,2,0) and R(0,0,0)
Computing the AO overlaps between R(-2,2,1) and R(0,0,0)
Computing the AO overlaps between R(-2,2,2) and R(0,0,0)
Computing the AO overlaps between R(-1,-2,-2) and R(0,0,0)
Computing the AO overlaps between R(-1,-2,-1) and R(0,0,0)
Computing the AO overlaps between R(-1,-2,0) and R(0,0,0)
Computing the AO overlaps between R(-1,-2,1) and R(0,0,0)
Computing the AO overlaps between R(-1,-2,2) and R(0,0,0)
Computing the AO overlaps between R(-1,-1,-2) and R(0,0,0)
Computing the AO overlaps between R(-1,-1,-1) and R(0,0,0)
Computing the AO overlaps between R(-1,-1,0) and R(0,0,0)
Computing the AO overlaps between R(-1,-1,1) and R(0,0,0)
Computing the AO overlaps between R(-1,-1,2) and R(0,0,0)
Computing the A

Computing the AO overlaps between R(0,-2,2) and R(0,0,0)
Computing the AO overlaps between R(0,-1,-2) and R(0,0,0)
Computing the AO overlaps between R(0,-1,-1) and R(0,0,0)
Computing the AO overlaps between R(0,-1,0) and R(0,0,0)
Computing the AO overlaps between R(0,-1,1) and R(0,0,0)
Computing the AO overlaps between R(0,-1,2) and R(0,0,0)
Computing the AO overlaps between R(0,0,-2) and R(0,0,0)
Computing the AO overlaps between R(0,0,-1) and R(0,0,0)
Computing the AO overlaps between R(0,0,1) and R(0,0,0)
Computing the AO overlaps between R(0,0,2) and R(0,0,0)
Computing the AO overlaps between R(0,1,-2) and R(0,0,0)
Computing the AO overlaps between R(0,1,-1) and R(0,0,0)
Computing the AO overlaps between R(0,1,0) and R(0,0,0)
Computing the AO overlaps between R(0,1,1) and R(0,0,0)
Computing the AO overlaps between R(0,1,2) and R(0,0,0)
Computing the AO overlaps between R(0,2,-2) and R(0,0,0)
Computing the AO overlaps between R(0,2,-1) and R(0,0,0)
Computing the AO overlaps between 

In [12]:
# Load sample file for S and St matrices and then 
# print the diagonal to check the orthonormality of the wavefunctions
S = sp.load_npz('res/S_ks_1.npz').todense()
print('S matrix:\n',np.diag(S))
St = sp.load_npz('res/St_ks_1.npz').todense()
print('St matrix:\n',np.diag(St))

S matrix:
 [0.99999687+0.j 0.99999772+0.j 1.00001651+0.j 1.00001607+0.j
 0.99998741+0.j 0.99998645+0.j 0.99908574+0.j 1.00007168+0.j
 0.99997962+0.j 0.99997791+0.j 1.0000099 +0.j 0.99999121+0.j
 1.00001772+0.j 0.99999561+0.j 1.00005599+0.j 1.00005979+0.j
 1.00005361+0.j 0.99999612+0.j 0.99959013+0.j 0.99958959+0.j
 0.99951307+0.j 1.00022009+0.j 0.99999687+0.j 0.99999772+0.j
 1.00001651+0.j 1.00001607+0.j 0.99998741+0.j 0.99998645+0.j
 0.99908574+0.j 1.00007168+0.j 0.99997962+0.j 0.99997791+0.j
 1.0000099 +0.j 0.99999121+0.j 1.00001772+0.j 0.99999561+0.j
 1.00005599+0.j 1.00005979+0.j 1.00005361+0.j 0.99999612+0.j
 0.99959013+0.j 0.99958959+0.j 0.99951307+0.j 1.00022009+0.j]
St matrix:
 [ 1.00090345+0.j  0.99885952+0.j -0.82253698+0.j  0.82254854+0.j
  1.00031489+0.j -0.99912937+0.j  0.99864727+0.j  1.00005677+0.j
  0.98932475+0.j  0.99193577+0.j  0.99807973+0.j  0.99898224+0.j
  0.99361279+0.j  0.94256035+0.j  0.94418512+0.j  0.99451763+0.j
 -1.00049856+0.j  0.99980439+0.j  0.99815321+