# Auxiliary functions for PySCF calculations 

**(based on test cases of Jieyang Gu  Email: jieyanggu792@gmail.com)**

In this tutorial, we demonstrate some auxiliary functions that could be used with PySCF calculations to get some properties relevant for NA-MD simulations, such as energies, gradients and, time-overlaps, etc.


## Table of contents
<a name="toc"></a>
1. [Importing needed libraries](#1)
2. [CISD calculations of $\text{HeH}^+$](#2)

   2.1. [Build the object](#2.1)
  
   2.2. [Compute energy and forces](#2.2)
  
   2.3. [Time-overlap calculation](#2.3)
  
3. [CASSCF calculations of $\text{HeH}^+$](#3)

   3.1. [Build the object](#3.1)
  
   3.2. [Compute energy and forces](#3.2)
  
   3.3. [Time-overlap calculation](#3.3)


### A. Learning objectives

* To be able to conduct PySCF calculations using Libra's auxiliary functions
* To be able extract the key infromation from the PySCF calculations (energies, gradients)
* To be able to compute time-overlaps of many-body wavefunctions with PySCF


### B. Use cases

* [process the PySCF calculations results](#use-1)
* [compute wavefunction time-overlaps with PySCF: CISD and CASSCF levels](#use-2)


### C. Functions

- `libra_py`
  - `packages`
    - `pyscf`
      - `implementations`
        - `casscf`
          - [`CASSCF`](#CASSCF-1)
          - [`compute_energy`](#compute_energy-1)
          - [`compute_gradient`](#compute_gradient-1)
          - [`set_geom_and_run_hf`](#set_geom_and_run_hf-1)
          - [`time_overlap_matrix`](#time_overlap_matrix-1)      
        - `cisd`
          - [`CISD`](#CISD-1)
          - [`compute_energy`](#compute_energy-2)
          - [`compute_gradient`](#compute_gradient-2)
          - [`set_geom_and_run_hf`](#set_geom_and_run_hf-2)
          - [`time_overlap_matrix`](#time_overlap_matrix-2)
      - `interfaces`
        - [`MolecularGeometry`](#MolecularGeometry-1)
            

## 1. Importing needed libraries 
<a name="1"></a>[Back to TOC](#toc)


In [1]:
import sys
from libra_py.packages.pyscf.implementations.cisd import CISD
from libra_py.packages.pyscf.implementations.casscf import CASSCF
from libra_py.packages.pyscf.interfaces import ElectronicStructureStrategy, MolecularGeometry
import numpy as np

## 2. CISD calculations of $\text{HeH}^{+}$
<a name="2"></a>[Back to TOC](#toc)

### 2.1. Build the object
<a name="2.1"></a> [Back to TOC](#toc)
<a name="MolecularGeometry-1"></a><a name="CISD-1"></a>

In [2]:
geom1 = MolecularGeometry(atom_labels=['He', 'H'], coords_angstrom=np.array([[0.0,0.0,0.0],[0.0,0.0,0.7746]]))
geom2 = MolecularGeometry(atom_labels=['He', 'H'], coords_angstrom=np.array([[0.0,0.0,0.0],[0.0,0.0,1.0]]))

cisd = CISD(nroots=3, basis='sto-3g', charge=1)

In [11]:
help(MolecularGeometry)

Help on class MolecularGeometry in module libra_py.packages.pyscf.interfaces:

class MolecularGeometry(builtins.object)
 |  MolecularGeometry(atom_labels: 'list[str]', coords_angstrom: 'np.ndarray') -> None
 |  
 |  MolecularGeometry(atom_labels: 'list[str]', coords_angstrom: 'np.ndarray')
 |  
 |  Methods defined here:
 |  
 |  __eq__(self, other)
 |      Return self==value.
 |  
 |  __init__(self, atom_labels: 'list[str]', coords_angstrom: 'np.ndarray') -> None
 |      Initialize self.  See help(type(self)) for accurate signature.
 |  
 |  __repr__(self)
 |      Return repr(self).
 |  
 |  ----------------------------------------------------------------------
 |  Data descriptors defined here:
 |  
 |  __dict__
 |      dictionary for instance variables (if defined)
 |  
 |  __weakref__
 |      list of weak references to the object (if defined)
 |  
 |  ----------------------------------------------------------------------
 |  Data and other attributes defined here:
 |  
 |  __annotat

In [10]:
help(CISD)

Help on class CISD in module libra_py.packages.pyscf.implementations.cisd:

class CISD(libra_py.packages.pyscf.interfaces.ElectronicStructureStrategy)
 |  CISD(mol: 'Optional[Any]' = None, nroots: 'int' = 1, basis: 'str' = 'sto-3g', unit: 'str' = 'Angstrom', charge: 'int' = 0) -> 'None'
 |  
 |  PySCF-based CISD backend for the universal ES interface.
 |  
 |  Method resolution order:
 |      CISD
 |      libra_py.packages.pyscf.interfaces.ElectronicStructureStrategy
 |      abc.ABC
 |      builtins.object
 |  
 |  Methods defined here:
 |  
 |  __init__(self, mol: 'Optional[Any]' = None, nroots: 'int' = 1, basis: 'str' = 'sto-3g', unit: 'str' = 'Angstrom', charge: 'int' = 0) -> 'None'
 |      Initialize self.  See help(type(self)) for accurate signature.
 |  
 |  compute_energy(self, root: 'int') -> 'float'
 |      Compute the energy for a given root.
 |  
 |  compute_gradient(self, root: 'int') -> 'np.ndarray'
 |      Compute the nuclear gradient for a given root.
 |  
 |  set_geom_a

### 2.2. Compute energy and forces 
<a name="2.2"></a> [Back to TOC](#toc)

First - for one geometry, then - for the other one
<a name="set_geom_and_run_hf-1"></a><a name="compute_energy-1"></a><a name="compute_gradient-1"></a>

In [3]:
cisd.set_geom_and_run_hf(geom1)
energies1 = [cisd.compute_energy(root) for root in range(3)]
print('Energies at geom1', energies1)

for root in range(3):
    grad1 = cisd.compute_gradient(root)
    print(F'Gradient root {root} geom1', grad1)

Energies at geom1 [-2.8515247344953685, -1.8213357011560944, -0.49687529985801904]
Gradient root 0 geom1 [[ 0.          0.          0.10046361]
 [ 0.          0.         -0.10046361]]
Gradient root 1 geom1 [[ 0.          0.          0.87513499]
 [ 0.          0.         -0.87513499]]
Gradient root 2 geom1 [[ 0.          0.          0.95922359]
 [ 0.          0.         -0.95922359]]


In [4]:
cisd.set_geom_and_run_hf(geom2)
energies2 = [cisd.compute_energy(root) for root in range(3)]
print('Energies at geom2', energies2)

for root in range(3):
    grad2 = cisd.compute_gradient(root)
    print(F'Gradient root {root} geom2', grad2)

Energies at geom2 [-2.8602051225798024, -2.0978611017333595, -0.7459600912918836]
Gradient root 0 geom2 [[ 0.          0.         -0.02737277]
 [ 0.          0.          0.02737277]]
Gradient root 1 geom2 [[ 0.          0.          0.47073289]
 [ 0.          0.         -0.47073289]]
Gradient root 2 geom2 [[ 0.          0.          0.30251057]
 [ 0.          0.         -0.30251057]]


### 2.3. Time-overlap calculation
<a name="2.3"></a> [Back to TOC](#toc)
<a name="time_overlap_matrix-1"></a>

In [5]:
overlap = cisd.time_overlap_matrix(3)
print('Time-overlap matrix', overlap)

Time-overlap matrix [[ 0.99692762  0.01881982  0.00438942]
 [ 0.00177257  0.96330424  0.02405012]
 [ 0.008177    0.02435486 -0.92265089]]


## 3. CASSCF calculations of $\text{HeH}^{+}$
<a name="3"></a> [Back to TOC](#toc)

### 3.1. Build the object
<a name="3.1"></a> [Back to TOC](#toc)
<a name="CASSCF-1"></a>

In [6]:
# instantiate the CASSCF strategy class with parameters for the test
casscf = CASSCF(norbcas=2, nelecas=2, nroots=3, basis='sto-3g', charge=1)

In [12]:
help(CASSCF)

Help on class CASSCF in module libra_py.packages.pyscf.implementations.casscf:

class CASSCF(libra_py.packages.pyscf.interfaces.ElectronicStructureStrategy)
 |  CASSCF(mol: 'Optional[Any]' = None, norbcas: 'int' = 0, nelecas: 'int' = 0, nroots: 'int' = 1, basis: 'str' = 'sto-3g', unit: 'str' = 'Angstrom', charge: 'int' = 0) -> 'None'
 |  
 |  PySCF-based CASSCF backend for the universal ES interface.
 |  
 |  Method resolution order:
 |      CASSCF
 |      libra_py.packages.pyscf.interfaces.ElectronicStructureStrategy
 |      abc.ABC
 |      builtins.object
 |  
 |  Methods defined here:
 |  
 |  __init__(self, mol: 'Optional[Any]' = None, norbcas: 'int' = 0, nelecas: 'int' = 0, nroots: 'int' = 1, basis: 'str' = 'sto-3g', unit: 'str' = 'Angstrom', charge: 'int' = 0) -> 'None'
 |      Initialize self.  See help(type(self)) for accurate signature.
 |  
 |  compute_energy(self, root: 'int') -> 'float'
 |      Compute the energy for a given root.
 |  
 |  compute_gradient(self, root: 'int'

### 3.2. Compute energy and forces 
<a name="3.2"></a> [Back to TOC](#toc)

First - for one geometry, then - for the other one
<a name="set_geom_and_run_hf-2"></a><a name="compute_energy-2"></a><a name="compute_gradient-2"></a>

In [7]:
# 1) wrap geometry set and HF in set_geom_and_run_hf method
casscf.set_geom_and_run_hf(geom1)

# 2) energy for root 0,1,2
energies1 = [casscf.compute_energy(root) for root in range(3)]
print('Energies at geom1', energies1)

# 3) gradients for all roots
for root in range(3):
    grad1 = casscf.compute_gradient(root)
    print(F'Gradient root {root} geom1', grad1)

CASSCF energy = -1.72324524516983
CASCI E = -1.72324524516983  E(CI) = -3.08956905338052  S^2 = 0.0000000
CASCI state-averaged energy = -1.72324524516983
CASCI energy for each state
  State 0 weight 0.333333  E = -2.85152473449537 S^2 = 0.0000000
  State 1 weight 0.333333  E = -1.82133570115609 S^2 = 0.0000000
  State 2 weight 0.333333  E = -0.49687529985802 S^2 = 0.0000000
Energies at geom1 [-2.8515247344953676, -1.8213357011560949, -0.4968752998580199]
--------------- StateAverageCASSCF gradients ---------------
         x                y                z
0 He     0.0000000000     0.0000000000     0.1004629711
1 H     0.0000000000     0.0000000000    -0.1004629711
----------------------------------------------
Gradient root 0 geom1 [[ 0.          0.          0.10046297]
 [ 0.          0.         -0.10046297]]


Overwritten attributes  converged  of <class 'pyscf.grad.sacasscf.Gradients'>
<class 'pyscf.grad.sacasscf.Gradients'> does not have attributes  e_tot ci


--------------- StateAverageCASSCF gradients ---------------
         x                y                z
0 He     0.0000000000     0.0000000000     0.8751332677
1 H     0.0000000000     0.0000000000    -0.8751332677
----------------------------------------------
Gradient root 1 geom1 [[ 0.          0.          0.87513327]
 [ 0.          0.         -0.87513327]]
--------------- StateAverageCASSCF gradients ---------------
         x                y                z
0 He     0.0000000000     0.0000000000     0.9592199850
1 H     0.0000000000     0.0000000000    -0.9592199850
----------------------------------------------
Gradient root 2 geom1 [[ 0.          0.          0.95921999]
 [ 0.          0.         -0.95921999]]


In [8]:
# 1) wrap geometry set and HF in set_geom_and_run_hf method
casscf.set_geom_and_run_hf(geom2)

# 2) energy for root 0,1,2
energies2 = [casscf.compute_energy(root) for root in range(3)]
print('Energies at geom1', energies2)

# 3) gradients for all roots
for root in range(3):
    grad2 = casscf.compute_gradient(root)
    print(F'Gradient root {root} geom2', grad2)

CASSCF energy = -2.01623567253983
CASCI E = -2.01623567253983  E(CI) = -3.07459009437983  S^2 = 0.0000000
CASCI state-averaged energy = -2.01623567253983
CASCI energy for each state
  State 0 weight 0.333333  E = -2.82399448520194 S^2 = 0.0000000
  State 1 weight 0.333333  E = -2.3573992878888 S^2 = 0.0000000
  State 2 weight 0.333333  E = -0.86731324452874 S^2 = 0.0000000
Energies at geom1 [-2.8239944852019354, -2.3573992878888017, -0.8673132445287399]
--------------- StateAverageCASSCF gradients ---------------
         x                y                z
0 He     0.0000000000     0.0000000000     0.0446178856
1 H     0.0000000000     0.0000000000    -0.0446178856
----------------------------------------------
Gradient root 0 geom2 [[ 0.          0.          0.04461789]
 [ 0.          0.         -0.04461789]]
--------------- StateAverageCASSCF gradients ---------------
         x                y                z
0 He     0.0000000000     0.0000000000     0.2974649458
1 H     0.00000

### 3.3. Time-overlap calculation
<a name="3.3"></a> [Back to TOC](#toc)
<a name="time_overlap_matrix-2"></a>

In [9]:
# time-overlap matrix for 3 roots
overlap = casscf.time_overlap_matrix(3)
print('Time-overlap matrix', overlap)

Time-overlap matrix [[ 0.99692762  0.01881982  0.00438942]
 [ 0.00177257  0.96330424  0.02405012]
 [-0.008177   -0.02435486  0.92265089]]
